=== joanflo/graph-it/graph/graph/data/scores.dtd
<?xml encoding="UTF-8"?>


<!-- Root -->
<!ELEMENT scores (category+)>

<!-- category -->
<!ELEMENT category (level+)>

<!-- level -->
<!ELEMENT level EMPTY>
<!ATTLIST level code CDATA #REQUIRED>
<!ATTLIST level moves CDATA #REQUIRED>

=== joanflo/graph-it/graph/graph/data/scores.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scores SYSTEM "scores.dtd">
<scores>
	<category>
		<level moves="0" code="0-0"/>
		<level moves="0" code="0-1"/>
		<level moves="0" code="0-2"/>
		<level moves="0" code="0-3"/>
		<level moves="0" code="0-4"/>
		<level moves="0" code="0-5"/>
		<level moves="0" code="0-6"/>
		<level moves="0" code="0-7"/>
		<level moves="0" code="0-8"/>
		<level moves="0" code="0-9"/>
		<level moves="0" code="0-10"/>
		<level moves="0" code="0-11"/>
		<level moves="0" code="0-12"/>
		<level moves="0" code="0-13"/>
		<level moves="0" code="0-14"/>
		<level moves="0" code="0-15"/>
		<level moves="0" code="0-16"/>
		<level moves="0" code="0-17"/>
		<level moves="0" code="0-18"/>
		<level moves="0" code="0-19"/>
		<level moves="0" code="0-20"/>
		<level moves="0" code="0-21"/>
		<level moves="0" code="0-22"/>
		<level moves="0" code="0-23"/>
		<level moves="0" code="0-24"/>
	</category>
	
	<category>
		<level moves="0" code="1-0"/>
		<level moves="0" code="1-1"/>
		<level moves="0" code="1-2"/>
		<level moves="0" code="1-3"/>
		<level moves="0" code="1-4"/>
		<level moves="0" code="1-5"/>
		<level moves="0" code="1-6"/>
		<level moves="0" code="1-7"/>
		<level moves="0" code="1-8"/>
		<level moves="0" code="1-9"/>
		<level moves="0" code="1-10"/>
		<level moves="0" code="1-11"/>
		<level moves="0" code="1-12"/>
		<level moves="0" code="1-13"/>
		<level moves="0" code="1-14"/>
		<level moves="0" code="1-15"/>
		<level moves="0" code="1-16"/>
		<level moves="0" code="1-17"/>
		<level moves="0" code="1-18"/>
		<level moves="0" code="1-19"/>
		<level moves="0" code="1-20"/>
		<level moves="0" code="1-21"/>
		<level moves="0" code="1-22"/>
		<level moves="0" code="1-23"/>
		<level moves="0" code="1-24"/>
	</category>

	<category>
		<level moves="0" code="2-0"/>
		<level moves="0" code="2-1"/>
		<level moves="0" code="2-2"/>
		<level moves="0" code="2-3"/>
		<level moves="0" code="2-4"/>
		<level moves="0" code="2-5"/>
		<level moves="0" code="2-6"/>
		<level moves="0" code="2-7"/>
		<level moves="0" code="2-8"/>
		<level moves="0" code="2-9"/>
		<level moves="0" code="2-10"/>
		<level moves="0" code="2-11"/>
		<level moves="0" code="2-12"/>
		<level moves="0" code="2-13"/>
		<level moves="0" code="2-14"/>
		<level moves="0" code="2-15"/>
		<level moves="0" code="2-16"/>
		<level moves="0" code="2-17"/>
		<level moves="0" code="2-18"/>
		<level moves="0" code="2-19"/>
		<level moves="0" code="2-20"/>
		<level moves="0" code="2-21"/>
		<level moves="0" code="2-22"/>
		<level moves="0" code="2-23"/>
		<level moves="0" code="2-24"/>
	</category>
	
	<category>
		<level moves="0" code="3-0"/>
		<level moves="0" code="3-1"/>
		<level moves="0" code="3-2"/>
		<level moves="0" code="3-3"/>
		<level moves="0" code="3-4"/>
		<level moves="0" code="3-5"/>
		<level moves="0" code="3-6"/>
		<level moves="0" code="3-7"/>
		<level moves="0" code="3-8"/>
		<level moves="0" code="3-9"/>
		<level moves="0" code="3-10"/>
		<level moves="0" code="3-11"/>
		<level moves="0" code="3-12"/>
		<level moves="0" code="3-13"/>
		<level moves="0" code="3-14"/>
		<level moves="0" code="3-15"/>
		<level moves="0" code="3-16"/>
		<level moves="0" code="3-17"/>
		<level moves="0" code="3-18"/>
		<level moves="0" code="3-19"/>
		<level moves="0" code="3-20"/>
		<level moves="0" code="3-21"/>
		<level moves="0" code="3-22"/>
		<level moves="0" code="3-23"/>
		<level moves="0" code="3-24"/>
	</category>
	
	<category>
		<level moves="0" code="4-0"/>
		<level moves="0" code="4-1"/>
		<level moves="0" code="4-2"/>
		<level moves="0" code="4-3"/>
		<level moves="0" code="4-4"/>
		<level moves="0" code="4-5"/>
		<level moves="0" code="4-6"/>
		<level moves="0" code="4-7"/>
		<level moves="0" code="4-8"/>
		<level moves="0" code="4-9"/>
		<level moves="0" code="4-10"/>
		<level moves="0" code="4-11"/>
		<level moves="0" code="4-12"/>
		<level moves="0" code="4-13"/>
		<level moves="0" code="4-14"/>
		<level moves="0" code="4-15"/>
		<level moves="0" code="4-16"/>
		<level moves="0" code="4-17"/>
		<level moves="0" code="4-18"/>
		<level moves="0" code="4-19"/>
		<level moves="0" code="4-20"/>
		<level moves="0" code="4-21"/>
		<level moves="0" code="4-22"/>
		<level moves="0" code="4-23"/>
		<level moves="0" code="4-24"/>
	</category>
	
	<category>
		<level moves="0" code="5-0"/>
		<level moves="0" code="5-1"/>
		<level moves="0" code="5-2"/>
		<level moves="0" code="5-3"/>
		<level moves="0" code="5-4"/>
		<level moves="0" code="5-5"/>
		<level moves="0" code="5-6"/>
		<level moves="0" code="5-7"/>
		<level moves="0" code="5-8"/>
		<level moves="0" code="5-9"/>
		<level moves="0" code="5-10"/>
		<level moves="0" code="5-11"/>
		<level moves="0" code="5-12"/>
		<level moves="0" code="5-13"/>
		<level moves="0" code="5-14"/>
		<level moves="0" code="5-15"/>
		<level moves="0" code="5-16"/>
		<level moves="0" code="5-17"/>
		<level moves="0" code="5-18"/>
		<level moves="0" code="5-19"/>
		<level moves="0" code="5-20"/>
		<level moves="0" code="5-21"/>
		<level moves="0" code="5-22"/>
		<level moves="0" code="5-23"/>
		<level moves="0" code="5-24"/>
	</category>
	
	<category>
		<level moves="0" code="6-0"/>
		<level moves="0" code="6-1"/>
		<level moves="0" code="6-2"/>
		<level moves="0" code="6-3"/>
		<level moves="0" code="6-4"/>
		<level moves="0" code="6-5"/>
		<level moves="0" code="6-6"/>
		<level moves="0" code="6-7"/>
		<level moves="0" code="6-8"/>
		<level moves="0" code="6-9"/>
		<level moves="0" code="6-10"/>
		<level moves="0" code="6-11"/>
		<level moves="0" code="6-12"/>
		<level moves="0" code="6-13"/>
		<level moves="0" code="6-14"/>
		<level moves="0" code="6-15"/>
		<level moves="0" code="6-16"/>
		<level moves="0" code="6-17"/>
		<level moves="0" code="6-18"/>
		<level moves="0" code="6-19"/>
		<level moves="0" code="6-20"/>
		<level moves="0" code="6-21"/>
		<level moves="0" code="6-22"/>
		<level moves="0" code="6-23"/>
		<level moves="0" code="6-24"/>
	</category>
	
	<category>
		<level moves="0" code="7-0"/>
		<level moves="0" code="7-1"/>
		<level moves="0" code="7-2"/>
		<level moves="0" code="7-3"/>
		<level moves="0" code="7-4"/>
		<level moves="0" code="7-5"/>
		<level moves="0" code="7-6"/>
		<level moves="0" code="7-7"/>
		<level moves="0" code="7-8"/>
		<level moves="0" code="7-9"/>
		<level moves="0" code="7-10"/>
		<level moves="0" code="7-11"/>
		<level moves="0" code="7-12"/>
		<level moves="0" code="7-13"/>
		<level moves="0" code="7-14"/>
		<level moves="0" code="7-15"/>
		<level moves="0" code="7-16"/>
		<level moves="0" code="7-17"/>
		<level moves="0" code="7-18"/>
		<level moves="0" code="7-19"/>
		<level moves="0" code="7-20"/>
		<level moves="0" code="7-21"/>
		<level moves="0" code="7-22"/>
		<level moves="0" code="7-23"/>
		<level moves="0" code="7-24"/>
	</category>
	
	<category>
		<level moves="0" code="8-0"/>
		<level moves="0" code="8-1"/>
		<level moves="0" code="8-2"/>
		<level moves="0" code="8-3"/>
		<level moves="0" code="8-4"/>
		<level moves="0" code="8-5"/>
		<level moves="0" code="8-6"/>
		<level moves="0" code="8-7"/>
		<level moves="0" code="8-8"/>
		<level moves="0" code="8-9"/>
		<level moves="0" code="8-10"/>
		<level moves="0" code="8-11"/>
		<level moves="0" code="8-12"/>
		<level moves="0" code="8-13"/>
		<level moves="0" code="8-14"/>
		<level moves="0" code="8-15"/>
		<level moves="0" code="8-16"/>
		<level moves="0" code="8-17"/>
		<level moves="0" code="8-18"/>
		<level moves="0" code="8-19"/>
		<level moves="0" code="8-20"/>
		<level moves="0" code="8-21"/>
		<level moves="0" code="8-22"/>
		<level moves="0" code="8-23"/>
		<level moves="0" code="8-24"/>
	</category>
	
	<category>
		<level moves="0" code="9-0"/>
		<level moves="0" code="9-1"/>
		<level moves="0" code="9-2"/>
		<level moves="0" code="9-3"/>
		<level moves="0" code="9-4"/>
		<level moves="0" code="9-5"/>
		<level moves="0" code="9-6"/>
		<level moves="0" code="9-7"/>
		<level moves="0" code="9-8"/>
		<level moves="0" code="9-9"/>
		<level moves="0" code="9-10"/>
		<level moves="0" code="9-11"/>
		<level moves="0" code="9-12"/>
		<level moves="0" code="9-13"/>
		<level moves="0" code="9-14"/>
		<level moves="0" code="9-15"/>
		<level moves="0" code="9-16"/>
		<level moves="0" code="9-17"/>
		<level moves="0" code="9-18"/>
		<level moves="0" code="9-19"/>
		<level moves="0" code="9-20"/>
		<level moves="0" code="9-21"/>
		<level moves="0" code="9-22"/>
		<level moves="0" code="9-23"/>
		<level moves="0" code="9-24"/>
	</category>
	
	<category>
		<level moves="0" code="10-0"/>
		<level moves="0" code="10-1"/>
		<level moves="0" code="10-2"/>
		<level moves="0" code="10-3"/>
		<level moves="0" code="10-4"/>
		<level moves="0" code="10-5"/>
		<level moves="0" code="10-6"/>
		<level moves="0" code="10-7"/>
		<level moves="0" code="10-8"/>
		<level moves="0" code="10-9"/>
		<level moves="0" code="10-10"/>
		<level moves="0" code="10-11"/>
		<level moves="0" code="10-12"/>
		<level moves="0" code="10-13"/>
		<level moves="0" code="10-14"/>
		<level moves="0" code="10-15"/>
		<level moves="0" code="10-16"/>
		<level moves="0" code="10-17"/>
		<level moves="0" code="10-18"/>
		<level moves="0" code="10-19"/>
		<level moves="0" code="10-20"/>
		<level moves="0" code="10-21"/>
		<level moves="0" code="10-22"/>
		<level moves="0" code="10-23"/>
		<level moves="0" code="10-24"/>
	</category>
	
	<category>
		<level moves="0" code="11-0"/>
		<level moves="0" code="11-1"/>
		<level moves="0" code="11-2"/>
		<level moves="0" code="11-3"/>
		<level moves="0" code="11-4"/>
		<level moves="0" code="11-5"/>
		<level moves="0" code="11-6"/>
		<level moves="0" code="11-7"/>
		<level moves="0" code="11-8"/>
		<level moves="0" code="11-9"/>
		<level moves="0" code="11-10"/>
		<level moves="0" code="11-11"/>
		<level moves="0" code="11-12"/>
		<level moves="0" code="11-13"/>
		<level moves="0" code="11-14"/>
		<level moves="0" code="11-15"/>
		<level moves="0" code="11-16"/>
		<level moves="0" code="11-17"/>
